### ISSUE TITLE
authUser null when accessing route at `/account` directly

### ISSUE THREAD

**Issue by deden** [taming-the-state-in-react/gatsby-firebase-authentication#1] opened 2017-12-15 13:49 UTC
Hi Robin, thanks for this great project. It inspired me a lot.

When trying the live demo, I encountered _TypeError: Cannot read property 'email' of null_ in this [link](https://react-firebase-authentication.wieruch.com/account)

I'm not sure if `withAuthorization(authCondition)` running correctly in that page, cmiiw.

I'm afk to running it in my machine, btw.

Cheers

**Comment by rwieruch** [comment] 2017-12-16 02:13
There was an old version of the repository in production. I just pushed a new version. Unfortunately it hasn't SSH yet, because the open source letsencrypt plugin I am using is waiting for a crucial fix...

For now, you can reach it under http://react-firebase-authentication.wieruch.com/

**Comment by ruslan-mystore** [comment] 2018-01-14 14:27
I have the same problem. 
Getting  blank page when reloading protected pages such "account" or "home"
But if i clicking in the Nav from "/" to "account" .... everything works fine

**Comment by rwieruch** [comment] 2018-01-14 14:57
@ruslan-mystore in your own application or the Demo application? Both should be up to date now. What error message do you get in the console log?

**Comment by ruslan-mystore** [comment] 2018-01-14 15:07
@rwieruch 
Just cloned this repo > npm install > added firebase config > signed in 
when coming from "/" to "/home" everything seems fine, but when reloading the page on "/home" the content of HomePage Component is empty.

I think the problem is with withAuthorization HOC
because if i changing this line:
```
export default withAuthorization(authCondition)(HomePage);
```

to this: 

```
export default HomePage
```


everything works fine

**Comment by creotip** [comment] 2018-01-16 09:46
Same problem here

**Comment by creotip** [comment] 2018-01-18 08:26
@rwieruch 
im trying to resolve the problem. Meanwhile you should reopen this issue

**Comment by rwieruch** [comment] 2018-01-18 11:58
Ok. I checked it too. Same problem for me. 

Somehow, but only in Gatsby ([because it works for a plain React application](https://github.com/rwieruch/react-firebase-authentication)), there is no incoming update for components depending on the context when the context has changed. In this case, the withAuthentication HOC sets the context at some point but it never runs an update for the somewhere underlying withAuthorization component. Thus the underlying component has no chance again to check if the authUser is in the context to render its underlying component. 

Someone able to check if this is somehow related to Gatsby? As mentioned, it works with the same mechanisms in create-react-app. CC @KyleAMathews

**Comment by ruslan-mystore** [comment] 2018-01-18 12:07
@rwieruch  
May be you should post this issue to the issues section in gatsby js ?

Tried to solve this too, without success.
I will continue to dig into it......

**Comment by creotip** [comment] 2018-01-25 16:10
I solved it by replacing context with redux....
Will post here a link later

**Comment by rwieruch** [comment] 2018-01-25 19:05
That's great! 👍 But I wouldn't want to include Redux in the starter project :( People using it should be able to decide on their own if they want to use React's local state, Redux, MobX or something else.

**Comment by creotip** [comment] 2018-01-27 23:02
@rwieruch 
I'm with you on that. 
You did an amazing work here, and in other repos that you have...but unfortunately we have here major bug, let's try to solve it

**Comment by rwieruch** [comment] 2018-01-28 07:07
Yes. Anything you know about a known issue in Gatsby regarding to the context API? The [plain React repository with create-react-app and context](https://github.com/rwieruch/react-firebase-authentication) works the same way without any bug.

**Comment by bzhr** [comment] 2018-03-22 11:53
is there an update to this issue? For me the user never gets attached to the state in the `withAuthentications.js` HOC, the user is always null 🙁

*Edit Note (maybe this makes a difference): I have added Twitter/Facebook Sign in, the current user is null after sign in with redirect, I don't use sign in with email and password.

**Comment by rwieruch** [comment] 2018-03-22 12:53
It's somehow related to React's context because it doesn't happen in the other repositories which implement the identical mechanism but without Gatsby. I hope the release for React 16.3 its new context API fixes it.

**Comment by bzhr** [comment] 2018-03-22 13:12
Is there an alternative way to implement this without context? The main thing I need to do is fire an action based on the `getRedirectResult` on `onAuthStateChanged`. In `onAuthStateChanged` the user is there, but the result from `getRedirectResult` is null.

**Comment by rwieruch** [comment] 2018-03-22 13:33
You can use [Redux](https://github.com/rwieruch/react-redux-firebase-authentication) or [MobX](https://github.com/rwieruch/react-mobx-firebase-authentication) instead for now. If you need a guide for it, use [this one](https://www.robinwieruch.de/complete-firebase-authentication-react-tutorial/).

**Comment by bzhr** [comment] 2018-03-22 15:32
thanks for the answer. What about instead of introducing a state management library like Redux or MobX I try to manage state in a different way e.g.: https://github.com/tylermcginnis/react-router-firebase-auth/blob/c5320acd36de2f646c5945e99d345ef5e28dc93d/src/components/index.js

**Comment by bzhr** [comment] 2018-03-22 15:51
Gatsby currently use React v15. What if I use Gatsby-React-Next to use v16? https://github.com/gatsbyjs/gatsby/tree/master/packages/gatsby-plugin-react-next

**Comment by rwieruch** [comment] 2018-03-31 13:21
Waiting for Gatsby using React 16.3. Then we can perhaps use the new context API which might solve the issue https://github.com/rwieruch/gatsby-firebase-authentication/pull/3

CC @bzhr @creotip @ruslan-mystore @deden

**Comment by jhlabs** [comment] 2018-04-20 16:37
@creotip could you post an example of how you solved this authentication with redux? I am struggling to implement a good solution.

**Comment by bzhr** [comment] 2018-04-20 18:21
@jhlabs I used this as a guide. /app is a client side route. 

https://github.com/gatsbyjs/gatsby/tree/master/examples/simple-auth

**Comment by bzhr** [comment] 2018-04-29 16:40
@rwieruch I have a proposal on how to solve this issue: https://github.com/bzhr/gatsby-firebase-authentication/tree/auth
If you think it's a good solution I will make a pull request. I've tested the build version of the web site and the /account route works when accessed directly. 
What I've done:
- With `gatsby-plugin-react-next` the latest version of React can be used, so context is available.
- I have used Gatsby's client side routes and pushed all user management routes to /app, like /app/home or /app/account
- The components structure is changed, Home, Account, SignIn... are now in componenets, App is in pages. 
- I removed BrowserRouter from the App component because if it's there `gatsby build` will fail. BrowserRouter can be introduced for the client side routes, though everything works as expected now, so the hassle wasn't worth it.

**Comment by rwieruch** [comment] 2018-04-30 02:18
@bzhr That's great news! Would you think `gatsby-plugin-react-next` is sufficient to fix this? I thought the issue may be related to React's Context API and that the latest React release may have fixed this. Because I have other projects which teach about Firebase in React (+ Gatsby), I wouldn't want to change the folder structure so much.

**Comment by bzhr** [comment] 2018-04-30 08:58
@rwieruch Two things are sufficient to fix this, one is `gatsby-plugin-react-next` to bring v16.3 features and another one is pushing all user management routes under client side route `/app/` so that React Router can be used (Gatsby doesn't support React Router), that's defined in `gatsby-node.js` file.

**Comment by rwieruch** [comment] 2018-04-30 09:35
@bzhr this sounds awesome! Would you be able to provide a PR for it? Really looking forward to this fix finally 🎉 The Context API needs to be adjusted too (see https://github.com/rwieruch/gatsby-firebase-authentication/pull/3)?

**Comment by bzhr** [comment] 2018-04-30 10:28
@rwieruch have a look in here: https://github.com/rwieruch/gatsby-firebase-authentication/pull/4

**Comment by rwieruch** [comment] 2018-06-01 02:51
Fixed in here: https://github.com/rwieruch/gatsby-firebase-authentication/pull/3

**Closed as completed by rwieruch** 2018-06-01 02:51 UTC
Labels: bug
